sudo: required
services:
  - docker

before_install:
  - docker build -t dhruvpateldp96/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dhruvpateldp96/docker-react npm run test


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-2-774145657424
  bucket_path: "docker"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
